### ISSUE TITLE
Cannot start limesurvey from helm

### ISSUE THREAD

**Issue by maffka123** [martialblog/helm-charts#101]
I am getting the following error inside the pod:
```shell
Info: Customizing Apache Listen port to 8080
Connection to mariadb.uzh.ch (130.60.216.228) 3306 port [tcp/*] succeeded!
Info: Generating config.php
Info: Using MySQL configuration
Info: Using TCP connection
Info: Setting PublicURL
Info: Creating security.php
Info: Check if database already provisioned. Nevermind the Stack trace.
Warning: No encryption keys were provided
Warning: A security.php config will be created by the application
Warning: THIS FILE NEEDS TO BE PERSISTENT
CException: DataBase version are not found, seems LimeSurvey are not installed. in /var/www/html/application/commands/UpdateDbCommand.php:36
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii/framework/console/CConsoleCommandRunner.php(71): UpdateDBCommand->run()
#1 /var/www/html/vendor/yiisoft/yii/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#2 /var/www/html/vendor/yiisoft/yii/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#3 /var/www/html/application/commands/console.php(77): CApplication->run()
#4 {main}
Running console.php install
CException: Invalid access data. Check your config.php db access data in /var/www/html/application/commands/InstallCommand.php:115
Stack trace:
#0 /var/www/html/application/commands/InstallCommand.php(50): InstallCommand->createDatabase()
#1 /var/www/html/vendor/yiisoft/yii/framework/console/CConsoleCommandRunner.php(71): InstallCommand->run()
#2 /var/www/html/vendor/yiisoft/yii/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#3 /var/www/html/vendor/yiisoft/yii/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#4 /var/www/html/application/commands/console.php(77): CApplication->run()
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.135.1.151. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.135.1.151. Set the 'ServerName' directive globally to suppress this message
[Mon Nov 04 10:21:13.613988 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.1.30 configured -- resuming normal operations
[Mon Nov 04 10:21:13.614018 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Nov 04 10:21:40.285055 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00170: caught SIGWINCH, shutting down gracefully
#5 {main}
```

Values are the following:
```shell
limesurvey:
              tablePrefix: "ls_"
            persistence:
              enabled: true
              storageClassName: idnas21zb
            livenessProbe:
              enabled: false
            readinessProbe:
              enabled: false
            externalDatabase:
              host: "mariadb.mydomain.com"
              database: "dbname"
              username: "limeuser"
              existingSecretConfig:
                passwordField: mtikhosecret
              existingSecret: limesurvey-pass
```
 wait-for-db succeeded, but the main container fails. I also tried without persistant volume with the same error
targetRevision: 0.9.0

**Comment by nitheesb** [comment]
I am having same issue, were you able to solve this issue?

**Comment by martialblog** [comment]
Hi, thanks for the hints. Unfortunately I don't use LS and Kubernetes these days, so I will archive this repo. Feel free to fork it and change it in any way you like.
